baseplate:
- bp_inspection_xml: true
hexaboard:
- hxb_inspection_xml: true
module:
- module_assembly_xml: true
- module_inspection_xml: true
- module_build_xml: true
- module_cure_cond_xml: true
- wirebond_xml: true
protomodule:
- proto_assembly_xml: true
- proto_inspection_xml: true
- proto_build_xml: true
- proto_cure_cond_xml: true
sensor:
- sensor_inspection_xml: true
testing:
- module_pedestal_xml: true
- hxb_pedestal_xml: true
- module_iv_xml: true
