baseplate:
- bp_cond_xml: false
hexaboard:
- hxb_cond_xml: false
module:
- module_assembly_xml: false
- module_build_xml: true
- module_cond_xml: false
- wirebond_xml: false
protomodule:
- proto_assembly_xml: false
- proto_build_xml: true
- proto_cond_xml: false
sensor:
- sensor_cond_xml: false
